Repository cs361fall2018/project-team-35, pull requests merged in 2018-10, with the labels that each got.

#8 Issue 1
  src/main/java/controllers/ApplicationController.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Ship.java
  src/main/java/cs361/battleships/models/ShipType.java
  src/main/java/cs361/battleships/models/Square.java
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/ShipTest.java
Labels: question

#39 Add prototype pictures
  wiki/Devin_1.jpg
  wiki/Devin_2.jpg
  wiki/Devin_3.jpg
  wiki/Final_1.jpg
Labels: add files

#40 Style boards to be horizontal
  src/main/java/assets/css/custom.css
  src/main/java/views/ApplicationController/index.ftl.html
Labels: enhancement

#49 Resolve Issue 37
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/views/ApplicationController/index.ftl.html
  src/main/java/views/layout/footer.ftl.html
Labels: enhancement

#46 Issue 41
  src/main/java/assets/css/custom.css
  src/main/java/views/ApplicationController/index.ftl.html
Labels: enhancement

#63 update board styles
  src/main/java/assets/css/custom.css
Labels: enhancement

#64 Add final prototypes
  wiki/Final_2.jpg
  wiki/Final_3.jpg
Labels: add files

#66 Update Devin boards, and Final_3
  wiki/Devin_1.jpg
  wiki/Devin_2.jpg
  wiki/Devin_3.jpg
  wiki/Final_3.jpg
Labels: add files
