Repository cs361fall2018/project-team-35, pull requests merged in 2018-11, with the labels that each got.

#74 Is 69
  src/main/java/controllers/ApplicationController.java
  src/main/java/cs361/battleships/models/Battleship.java
  src/main/java/cs361/battleships/models/Destroyer.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Minesweeper.java
  src/main/java/cs361/battleships/models/Ship.java
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/GameTest.java
  src/test/java/cs361/battleships/models/ShipTest.java
Labels: Code Refraction

#77 Issue 73
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
Labels: feature

#80 Issue 79
  src/main/java/cs361/battleships/models/Board.java
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: bug

#76 Is 71 - Sonar Pulse Backend
  src/main/java/controllers/ApplicationController.java
  src/main/java/controllers/AttackGameAction.java
  src/main/java/cs361/battleships/models/AttackStatus.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/GameTest.java
Labels: feature

#85 Is 72 Front End for Sonar Pulse
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/views/ApplicationController/index.ftl.html
Labels: feature

#92 Is 89
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/controllers/ApplicationController.java
  src/main/java/controllers/PlacementGameAction.java
  src/main/java/cs361/battleships/models/Battleship.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Destroyer.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Minesweeper.java
  src/main/java/cs361/battleships/models/Ship.java
  src/main/java/cs361/battleships/models/Submarine.java
  src/main/java/views/ApplicationController/index.ftl.html
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/GameTest.java
Labels: feature
